### ISSUE TITLE
Changing tree's input makes tree into static list

### ISSUE THREAD

**Issue by kmader** [trestletech/shinyTree#12]
I am having issues with the plugin when the input is changed after it has been created for the first time. I have only tested in Chrome 39.0.2171.95 and Safari 8.0.2 but I guess it extends to other browsers 

Live Demo: https://4quant.shinyapps.io/BucketBrowser/
The tree is created using the standard (server.R)
```
output$tree <- renderTree({
    bucket.tree()
  })
```
and correspondingly (ui.R)
```
shinyTree("tree",search=TRUE,dragAndDrop=TRUE,checkbox=TRUE)
```

Change the bucket source or the file filter and the tree becomes static

**Comment by trestletech** [comment]
Thanks for the report! Just pushed a fix.
