### ISSUE TITLE
shiny tree checkbox state *partially selected* to *not selected*

### ISSUE THREAD

**Issue by jangorecki** [trestletech/shinyTree#15]
Considering a list with particular selection:
![image](https://cloud.githubusercontent.com/assets/3627377/5949567/754321a8-a74f-11e4-9de6-4cb20c072cfa.png)
State of the `SubListA` can be called *partially selected*. Now if I would click on the `SubListA` with my intent to remove `SubListA` and its leafs selection but I end up with `SubListA` and all leaves selected. Normally it would not be a problem but selecting list elements triggers evaluation of functions for which more selected items means more complexity. In such case it would be much better to de-select root and leafs than selecting them.
Is there any way I can change that behavior and when clicking on partially selected root have it de-selected instead of selecting the root and leafs?
If no, is there any way to remove *partially selected* state?

**Comment by trestletech** [comment]
Unfortunately that's not a feature supported by the underlying JS library, jsTree. 

Feel free to open a request with that project: https://github.com/vakata/jstree. If they are able to add that in, I'd be happy to add it to ShinyTree. I'll close this issue now, since it's not possible at the moment.

**Comment by martijnmolenaar** [comment]
This worked for me: the shinyTree function get_selected(input$tree, format = "names") will return 'leaf2' and 'leaf3' here. Its 'ancestry' attributes are 'SublistA' and 'root2', while those are not in the vector. Hence, you can infer that those are partially selected.
